Repository SkalskiP/make-sense, pull requests merged in 2019-09, with the labels that each got.

#38 Keyboard shortcuts 2
  src/data/ContextType.ts
  src/data/RectExportFormatData.ts
  src/logic/context/BaseContext.ts
  src/logic/context/ContextManager.ts
  src/logic/context/EditorContext.ts
  src/logic/context/PopupContext.ts
  src/logic/render/BaseRenderEngine.ts
  src/logic/render/PointRenderEngine.ts
  src/logic/render/PolygonRenderEngine.ts
  src/logic/render/RectRenderEngine.ts
  src/settings/_Settings.scss
  src/store/general/actionCreators.ts
  src/store/general/types.ts
  src/store/selectors/GeneralSelector.ts
  src/utils/MouseEventUtil.ts
  src/views/EditorView/BottomNavigationBar/BottomNavigationBar.scss
  src/views/EditorView/BottomNavigationBar/BottomNavigationBar.tsx
  src/views/EditorView/Editor/Editor.tsx
  src/views/EditorView/EditorContainer/EditorContainer.tsx
  src/views/PopupView/GenericYesNoPopup/GenericYesNoPopup.tsx
Labels: enhancement

#47 Zoom in and out preperation
  src/App.tsx
  src/logic/actions/EditorActions.ts
  src/logic/actions/ImageActions.ts
  src/logic/actions/PopupActions.ts
  src/logic/context/ContextManager.ts
  src/logic/context/EditorContext.ts
  src/logic/context/PopupContext.ts
  src/logic/initializer/AppInitializer.ts
  src/settings/Settings.ts
  src/settings/_Settings.scss
  src/staticModels/EditorModel.ts
  src/staticModels/PlatformModel.ts
  src/store/Actions.ts
  src/store/general/actionCreators.ts
  src/store/general/reducer.ts
  src/store/general/types.ts
  src/store/selectors/GeneralSelector.ts
  src/utils/PlatformUtil.ts
  src/views/EditorView/Editor/Editor.tsx
  src/views/EditorView/EditorContainer/EditorContainer.tsx
  src/views/EditorView/SideNavigationBar/ImagesList/ImagesList.tsx
  src/views/EditorView/SideNavigationBar/LabelsToolkit/LabelsToolkit.tsx
  src/views/EditorView/SideNavigationBar/SideNavigationBar.scss
  src/views/EditorView/SideNavigationBar/SideNavigationBar.tsx
  src/views/PopupView/ExitProjectPopup/ExitProjectPopup.tsx
  src/views/PopupView/ExportLabelsPopup/ExportLabelPopup.tsx
  src/views/PopupView/InsertLabelNamesPopup/InsertLabelNamesPopup.tsx
  src/views/PopupView/LoadLabelNamesPopup/LoadLabelNamesPopup.tsx
  src/views/PopupView/LoadMoreImagesPopup/LoadMoreImagesPopup.tsx
Labels: improvement

#49 Zoom in n out initial version
  src/App.tsx
  src/data/EditorData.ts
  src/logic/actions/EditorActions.ts
  src/logic/actions/ImageActions.ts
  src/logic/actions/ViewPortActions.ts
  src/logic/context/ContextManager.ts
  src/logic/context/EditorContext.ts
  src/logic/render/PointRenderEngine.ts
  src/logic/render/PolygonRenderEngine.ts
  src/logic/render/PrimaryEditorRenderEngine.ts
  src/logic/render/RectRenderEngine.ts
  src/settings/Settings.ts
  src/settings/ViewPointSettings.ts
  src/staticModels/EditorModel.ts
  src/utils/DirectionUtil.ts
  src/utils/ImageUtil.ts
  src/utils/NumberUtil.ts
  src/utils/RenderEngineUtil.ts
  src/utils/SizeUtil.ts
  src/views/EditorView/BottomNavigationBar/BottomNavigationBar.tsx
  src/views/EditorView/Editor/Editor.scss
  src/views/EditorView/Editor/Editor.tsx
  src/views/EditorView/EditorView.tsx
  src/views/EditorView/SideNavigationBar/ImagesList/ImagesList.tsx
Labels: enhancement

#60 done
  src/App.scss
  src/App.tsx
  src/data/info/EditorFeatureData.ts
  src/logic/helpers/CSSHelper.ts
  src/logic/initializer/AppInitializer.ts
  src/settings/_Settings.scss
  src/store/selectors/AISelector.ts
  src/views/Common/TextInput/TextInput.scss
  src/views/Common/UnderlineTextButton/UnderlineTextButton.scss
  src/views/EditorView/BottomNavigationBar/BottomNavigationBar.scss
  src/views/EditorView/SideNavigationBar/ImagePreview/ImagePreview.scss
  src/views/EditorView/SideNavigationBar/ImagePreview/ImagePreview.tsx
  src/views/EditorView/SideNavigationBar/LabelInputField/LabelInputField.scss
  src/views/EditorView/SideNavigationBar/LabelsToolkit/LabelsToolkit.scss
  src/views/EditorView/StateBar/StateBar.scss
  src/views/EditorView/TopNavigationBar/TopNavigationBar.scss
  src/views/EditorView/VerticalEditorButton/VerticalEditorButton.scss
  src/views/PopupView/GenericYesNoPopup/GenericYesNoPopup.scss
Labels: enhancement, improvement

#61 Rects control panels
  src/App.tsx
  src/logic/actions/EditorActions.ts
  src/logic/actions/ViewPortActions.ts
  src/logic/render/RectRenderEngine.ts
  src/model/EditorModel.ts
  src/staticModels/EditorModel.ts
  src/store/Actions.ts
  src/store/general/actionCreators.ts
  src/store/general/reducer.ts
  src/store/general/types.ts
  src/store/selectors/GeneralSelector.ts
  src/views/EditorView/Editor/Editor.tsx
  src/views/EditorView/LabelControlPanel/LabelControlPanel.scss
  src/views/EditorView/LabelControlPanel/LabelControlPanel.tsx
  src/views/EditorView/SideNavigationBar/RectLabelsList/RectLabelsList.tsx
  src/views/EditorView/ToolBox/ToolBox.tsx
Labels: enhancement, improvement

#64 fix bug [Unable to preventDefault inside passive event listener]
  src/logic/initializer/AppInitializer.ts
Labels: bug

#65 Label assignment mechanism refactor
  src/data/enums/PopupWindowType.ts
  src/logic/actions/AIActions.ts
  src/logic/actions/LabelActions.ts
  src/logic/context/ContextManager.ts
  src/logic/export/PointLabelsExport.ts
  src/logic/export/PolygonLabelsExporter.ts
  src/logic/export/RectLabelsExporter.ts
  src/logic/export/__tests__/PolygonLabelsExporter.test.ts
  src/logic/render/PointRenderEngine.ts
  src/logic/render/PolygonRenderEngine.ts
  src/logic/render/RectRenderEngine.ts
  src/store/Actions.ts
  src/store/labels/actionCreators.ts
  src/store/labels/reducer.ts
  src/store/labels/types.ts
  src/store/selectors/LabelsSelector.ts
  src/utils/LabelUtil.ts
  src/views/EditorView/SideNavigationBar/LabelInputField/LabelInputField.tsx
  src/views/EditorView/SideNavigationBar/LabelsToolkit/LabelsToolkit.tsx
  src/views/EditorView/SideNavigationBar/PointLabelsList/PointLabelsList.tsx
  src/views/EditorView/SideNavigationBar/PolygonLabelsList/PolygonLabelsList.tsx
  src/views/EditorView/SideNavigationBar/RectLabelsList/RectLabelsList.tsx
  src/views/EditorView/TopNavigationBar/TopNavigationBar.tsx
  src/views/PopupView/ExitProjectPopup/ExitProjectPopup.tsx
  src/views/PopupView/InsertLabelNamesPopup/InsertLabelNamesPopup.scss
  src/views/PopupView/InsertLabelNamesPopup/InsertLabelNamesPopup.tsx
  src/views/PopupView/LoadLabelNamesPopup/LoadLabelNamesPopup.tsx
  src/views/PopupView/PopupView.tsx
Labels: enhancement, improvement

#66 Suggested labels part 2
  public/ico/checkbox-checked.png
  public/ico/checkbox-checked_.png
  public/ico/checkbox-unchecked.png
  public/ico/checkbox-unchecked_.png
  src/data/enums/PopupWindowType.ts
  src/logic/actions/AIActions.ts
  src/logic/actions/__test__/AIActions.test.ts
  src/logic/helpers/CSSHelper.ts
  src/store/Actions.ts
  src/store/ai/actionCreators.ts
  src/store/ai/reducer.ts
  src/store/ai/types.ts
  src/store/selectors/AISelector.ts
  src/views/PopupView/ExportLabelsPopup/ExportLabelPopup.scss
  src/views/PopupView/GenericYesNoPopup/GenericYesNoPopup.tsx
  src/views/PopupView/PopupView.tsx
  src/views/PopupView/SuggestLabelNamesPopup/SuggestLabelNamesPopup.scss
  src/views/PopupView/SuggestLabelNamesPopup/SuggestLabelNamesPopup.tsx
Labels: enhancement
